apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-wojz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jhutar-tenant/my-app/devfile-sample-python-basic-wojz@sha256:1a1f97649c8746d9473d8cb4e0c4b575ee447e071e1c4446f044644217dc10a7
        name: my-python
        resources: {}
status: {}
